// <auto-generated />
using DataKendaraan.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataKendaraan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220809061357_ConnectDb")]
    partial class ConnectDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataKendaraan.Models.Kendaraan", b =>
                {
                    b.Property<string>("NoRegistrasi")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BahanBakar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPemilik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TahunPembuatan")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Warna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NoRegistrasi");

                    b.ToTable("Kendaraan");
                });
#pragma warning restore 612, 618
        }
    }
}
